-- ============================================================================
-- 100_family.sql  —  family assets (dedicated namespace)
--
-- Faithful PostgreSQL port of the legacy SQL Server family tables
-- (dbo.FamilyPeople/Assets/Holdings/Prices/Accounts/CashFlows/History).
-- Kept in its own `family` namespace instead of the canonical portfolio ledger
-- so the existing per-person absolute quantity/cost write semantics and the
-- current API/UI contract are preserved exactly.
--
-- Idempotent: safe to run against an existing database (CREATE ... IF NOT EXISTS).
-- date_key columns are Jalali text 'YYYY/MM/DD', identical to the legacy model
-- and to what the React client expects.
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS family;

-- ----------------------------------------------------------------------------
-- family.people
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS family.people (
    person_id  integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       text        NOT NULL,
    sort_order integer     NOT NULL DEFAULT 0,
    is_active  boolean     NOT NULL DEFAULT true,
    CONSTRAINT family_people_name_not_blank CHECK (length(btrim(name)) > 0)
);

-- ----------------------------------------------------------------------------
-- family.assets
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS family.assets (
    asset_id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            text    NOT NULL,
    category        text    NOT NULL DEFAULT 'stock',
    commission_rate double precision NOT NULL DEFAULT 0.0088,
    symbol          text,
    sort_order      integer NOT NULL DEFAULT 0,
    is_active       boolean NOT NULL DEFAULT true,
    CONSTRAINT family_assets_name_not_blank CHECK (length(btrim(name)) > 0),
    CONSTRAINT family_assets_category_chk CHECK (category IN ('stock','gold','dollar','other'))
);

-- ----------------------------------------------------------------------------
-- family.holdings
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS family.holdings (
    person_id  integer NOT NULL REFERENCES family.people(person_id) ON DELETE CASCADE,
    asset_id   integer NOT NULL REFERENCES family.assets(asset_id) ON DELETE CASCADE,
    quantity   double precision NOT NULL DEFAULT 0,
    cost_basis double precision NOT NULL DEFAULT 0,
    CONSTRAINT family_holdings_pk PRIMARY KEY (person_id, asset_id)
);

-- ----------------------------------------------------------------------------
-- family.prices
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS family.prices (
    date_key text    NOT NULL,
    asset_id integer NOT NULL REFERENCES family.assets(asset_id) ON DELETE CASCADE,
    price    double precision NOT NULL,
    CONSTRAINT family_prices_pk PRIMARY KEY (date_key, asset_id)
);

CREATE INDEX IF NOT EXISTS ix_family_prices_asset ON family.prices (asset_id, date_key DESC);

-- ----------------------------------------------------------------------------
-- family.accounts
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS family.accounts (
    person_id    integer NOT NULL PRIMARY KEY REFERENCES family.people(person_id) ON DELETE CASCADE,
    cash_balance double precision NOT NULL DEFAULT 0
);

-- ----------------------------------------------------------------------------
-- family.cash_flows
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS family.cash_flows (
    id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_key  text    NOT NULL,
    amount    double precision NOT NULL,
    direction text    NOT NULL,
    note      text,
    CONSTRAINT family_cash_flows_direction_chk CHECK (direction IN ('in','out'))
);

CREATE INDEX IF NOT EXISTS ix_family_cash_flows_date ON family.cash_flows (date_key DESC, id DESC);

-- ----------------------------------------------------------------------------
-- family.history   (daily total-value snapshots)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS family.history (
    date_key    text NOT NULL PRIMARY KEY,
    total_value double precision NOT NULL,
    change_value double precision NOT NULL DEFAULT 0,
    change_pct   double precision NOT NULL DEFAULT 0,
    recorded_at  timestamptz NOT NULL DEFAULT now()
);
