-- ============================================================================
-- 110_family_broker.sql  —  brokerage (Agah) account links for family people
--
-- One Agah online account per family person. Credentials are AES-GCM encrypted
-- at rest (secret_cipher/secret_nonce); the encryption key lives in .env
-- (CDF_SECRET_KEY) and never in the database.
--
-- `broker_snapshots` keeps a raw JSON audit of each imported portfolio so a
-- failed parse can be re-examined without re-login.
--
-- Idempotent: safe to run against an existing database.
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS family;

-- ----------------------------------------------------------------------------
-- family.broker_accounts
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS family.broker_accounts (
    broker_account_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id         integer NOT NULL UNIQUE REFERENCES family.people(person_id) ON DELETE CASCADE,
    broker            text    NOT NULL DEFAULT 'agah',
    username          text    NOT NULL,
    secret_cipher     text,
    secret_nonce      text,
    is_active         boolean NOT NULL DEFAULT true,
    last_synced_at    timestamptz,
    last_status       text,
    last_error        text,
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT family_broker_accounts_username_not_blank CHECK (length(btrim(username)) > 0)
);

CREATE INDEX IF NOT EXISTS ix_family_broker_accounts_broker ON family.broker_accounts (broker);

-- ----------------------------------------------------------------------------
-- family.broker_snapshots   (raw import audit)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS family.broker_snapshots (
    id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    person_id   integer NOT NULL REFERENCES family.people(person_id) ON DELETE CASCADE,
    broker      text    NOT NULL DEFAULT 'agah',
    captured_at timestamptz NOT NULL DEFAULT now(),
    ok          boolean NOT NULL DEFAULT true,
    error       text,
    payload     jsonb   NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_family_broker_snapshots_person ON family.broker_snapshots (person_id, captured_at DESC);
